### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by messersc** [BIMSBbioinfo/pigx_chipseq#135]
Hi,

this is my first time trying to run pigz and touching guix, so I will try to go by the documentation and put my questions here so we can improve the documentation.

# Installation
After `guix package -i pigx-chipseq` and putting guix in my PATH as proposed by guix (`export PATH="/home/cmessers/.guix-profile/bin${PATH:+:}$PATH"`), do I need to run `guix environment -l guix.scm`? Apparently the last command generates an environment for development, but to use the pipeline it does not appear to be necessary.

# command name?

In my installation, the command appears to be `pigx-chipseq` and not `pigx chipseq` as the docs say.

# Replicates

The docs say
> The current sample sheet does not support multiple technical replicates for one sample, so replicates need to be combined prior to running the pipeline.

i get that this is a limitation of MACS2. How should biological replicates be handled?

Further, I was confused by the sample sheet regarding this same point.

The example includes

```
    Peaks4:
        ChIP:
            # multiple samples can be used as treatment
            - ChIP1
            - ChIP2
        Cont:
            # multiple samples can be used as control
            - Cont1
            - Cont2
```

So how are ChIP1 and ChIP2 handled here?

Otherwise the running the tests went fine.

Thanks for the effort,
Clemens
