### ISSUE TITLE
in sample_sheet.yaml: check if paired really contains two fastq files 

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#38]
Specifically check for this case:
```
samples:
  chip:
    fastq:
      - one.fastq
    library: "paired"
[ ... ]
```

This issue might become depricated due to sample sheet parsing from tables, but is relevant if users can also provide sample sheet as yaml file.
