### ISSUE TITLE
broad peaks have to be defined for every Peak sample

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#65]
if broad argument is given to general macs2 settings like this:
```
general:
  assembly: hg19
  params:
    extend: 200
    scale_bw: 'no'
    bowtie2:
        k: 4
        X: 2000
        local: ''
        no-discordant: ''
        no-mixed: ''
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: 1
        q: 0.05
        format: 'BAMPE'
        nomodel: ''
        shift: -100
        extsize: 200
        broad: ''
```
Then snakemake will not know that all samples should be handled as broad peaks, 
because the macs2 suffix `broadPeak` is derived from `CUSTOM_PARAMS` dict. 

Right now the way to handle this is to add the custom param broad to every sample.

A solution to this issue could be that we use the custom params to overwrite the default general settings (i.e. config dict) on a per sample basis, such that we do not have to deal with two dictionaries to handle settings.
